version: 0.0
os: linux

files:
  - source: /        # GitHub repository root directory (where your app resides)
    destination: /home/ubuntu/myapp 
    
hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
